# Generated by Django 6.1 on 2026-08-17 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('kakao_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=60)),
                ('preset', models.CharField(default='normal', max_length=16)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
