# Generated by Django 6.1 on 2026-08-16 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('in_progress', '이동중'), ('completed', '완료'), ('cancelled', '취소')], default='in_progress', max_length=12)),
                ('from_name', models.CharField(blank=True, default='', max_length=120)),
                ('to_name', models.CharField(blank=True, default='', max_length=120)),
                ('total_minutes', models.IntegerField(default=0)),
                ('exposure_load', models.IntegerField(default=0)),
                ('outdoor_minutes', models.IntegerField(default=0)),
                ('uv_minutes', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
