# Generated by Django 6.1 on 2026-08-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
