# Generated by Django 6.1 on 2026-08-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_account_alter_trip_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=8)),
                ('node_id', models.CharField(db_index=True, max_length=32)),
                ('route_no', models.CharField(max_length=16)),
                ('route_id', models.CharField(blank=True, default='', max_length=32)),
                ('minutes', models.IntegerField()),
                ('stations_left', models.IntegerField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
