"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

load_dotenv()


def _csv_env(name: str, default: str = "") -> list[str]:
    """콤마 구분 env → 리스트. 공백·빈 항목 제거.

    미설정 시 빈 문자열 하나가 남으면 corsheaders.E013으로 서버가 아예 기동하지 않는다
    ("Origin '' is missing scheme or netloc"). 배포 중 .env 한 줄 누락으로 500도 아닌
    부팅 실패를 만나지 않도록 여기서 걸러낸다.
    """
    return [v.strip() for v in os.getenv(name, default).split(",") if v.strip()]


CORS_ALLOWED_ORIGINS = _csv_env("CORS_ALLOWED_ORIGINS")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# 배포 도메인은 env로 (예: ALLOWED_HOSTS=waywell.testgogo.site). 미설정 시 로컬만 허용.
ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'apps.accounts',
    'apps.environment',
    'apps.places',
    'apps.routes',
    'apps.trips',
    'apps.notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

# 한국 서비스 — 리포트 날짜 집계가 KST 기준이어야 함 (timezone.localtime()이 KST 반환)
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# collectstatic 대상. DEBUG=False(배포)에서는 Django가 static을 서빙하지 않으므로
# `manage.py collectstatic` 후 Nginx가 이 디렉터리를 /static/ 으로 서빙해야 admin이 깨지지 않는다.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 캐시 — 경로 후보 캐시·LLM 설명 캐시가 함께 쓴다.
# 기본값(LocMemCache)은 프로세스별로 분리돼, gunicorn 워커 N개면 캐시도 N벌이 되어
# 유료 외부 API를 워커 수만큼 중복 호출한다. 파일 기반은 워커끼리 공유된다.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / '.cache',
        'TIMEOUT': 600,
        'OPTIONS': {'MAX_ENTRIES': 1000},
    }
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# E-04 도착정보 크롤러가 주기 수집할 대표 정류소 (city_code, node_id, label)
TAGO_CRAWL_STATIONS = [
    ("25", "DJB8001793", "세종 송강전통시장"),
]
# 폴백 스냅샷 유효 시간(초): 이보다 오래된 수집분은 무시
ARRIVAL_SNAPSHOT_TTL = 300

# 레이트리밋 — 유료 외부 API(ODsay/기상청/카카오/TAGO) 프록시 남용 방지.
# IP(게스트)·계정별 상한. 배포 시 프록시 뒤면 X-Forwarded-For 처리(NUM_PROXIES) 필요.
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_ANON", "120/min"),
        "user": os.getenv("THROTTLE_USER", "240/min"),
        "auth": os.getenv("THROTTLE_AUTH", "30/min"),  # 로그인(카카오) 엔드포인트 전용 상한
        # LLM 경로 설명(B-09) 전용 — OpenAI는 호출당 과금이라 다른 프록시보다 훨씬 빡빡하게.
        "llm": os.getenv("THROTTLE_LLM", "20/min"),
    },
}

# 프로덕션 HTTPS 하드닝 (옵트인: SECURE_HTTPS=True). Nginx 뒤 배포 기준.
# 로컬(http) 개발을 깨지 않도록 기본 off — 배포 시에만 켠다.
if os.getenv("SECURE_HTTPS", "False") == "True":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # Nginx가 X-Forwarded-Proto 전달
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1년
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
